data_files:
  submission_template: data/raw/submission.csv
  test: data/raw/data_test.csv
  train: data/raw/data_train.csv
dataset:
  freq: B
  missing_values: false
  n_features: 8
  n_test_rows: 778
  n_train_rows: 3498
  test_end: '2026-05-29'
  test_start: '2023-06-01'
  train_end: '2023-05-31'
  train_start: '2010-01-04'
forecast:
  end_date: '2026-05-29'
  frequency: B
  start_date: '2023-06-01'
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
metrics:
- RMSE
- MAPE
- MAE
- R2
mlflow:
  experiment_name: rupiah_resilience_usdidr
  tracking_uri: mlruns
paths:
  metrics: results/metrics/
  models_saved: results/models/
  plots: results/plots/
  processed_data: data/processed/
  raw_data: data/raw/
  results: results/
  submissions: data/submissions/
project:
  date_column: Date
  feature_columns:
  - OIL
  - GOLD
  - SP500
  - IHSG
  - VIX
  - CPI
  - BI_rate
  - US_rate
  group_number: XX
  name: "Rupiah Resilience \u2014 USD/IDR Forecasting"
  random_seed: 42
  target_column: USDIDR
scenarios:
- label: 80/20 Split
  name: scenario_1
  test_ratio: 0.2
  train_ratio: 0.8
- label: 70/30 Split
  name: scenario_2
  test_ratio: 0.3
  train_ratio: 0.7
- label: 60/40 Split
  name: scenario_3
  test_ratio: 0.4
  train_ratio: 0.6
